# Generated by Django 5.2.4 on 2025-08-06 05:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название задачи')),
                ('description', models.TextField(verbose_name='Описание задачи')),
                ('handler_path', models.CharField(max_length=255, verbose_name='Путь к обработчику')),
                ('timeout', models.IntegerField(blank=True, null=True, verbose_name='Максимальное времы выполнения')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.JSONField(blank=True, default=dict)),
                ('arrival_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает выполнения'), ('IN_PROGRESS', 'Вполняется'), ('COMPLETED', 'Завершена')], db_index=True, default='PENDING', max_length=16)),
                ('outcome', models.CharField(blank=True, choices=[('SUCCESS', 'Успешно'), ('FAILED', 'Провалено')], max_length=16, null=True)),
                ('result_data', models.JSONField(blank=True, null=True)),
                ('task_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.tasktype')),
            ],
            options={
                'ordering': ('-arrival_date',),
            },
        ),
    ]
